<!-- templates/users/new.phtml -->
<h1> Registration Form <h1>
<form action="/users" method="post">
  <div>
    <label>
        Имя :
      <input type="text" required placeholder="Enter nickname" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>"/>
    </label>
    <?php if (isset($errors['nickname'])): ?>
      <div><?= $errors['nickname'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email : 
      <input type="email" required placeholder="Enter email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
    </label>
    <?php if (isset($errors['email'])): ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Sign Up">
</form>
