<a href="/users/new">add user</a>
<?php if (count($flash) !== 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li> <?= $message ?> </>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
    <div>
        <a href=/users/auth>Log In </a>
    </div>
<table>
<?php foreach ($users as $key => $user) : ?>
    <div>
    Name : <a href="/users/<?= htmlspecialchars($key) ?>"><?= htmlspecialchars($user['nickname']) ?></a>
    </div>
    <div>
    Email : <?= htmlspecialchars($user['email']) ?>
    </div>
<?php endforeach ?>
</table>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a>
<a href="?page=<?= $page + 1 ?>">Next</a>
