<a href="/users?page=2&per=5">all_users with_pages</a>
<?php if (count($flash) !== 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li> <?= $message ?> </>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<table>
<?php foreach ($users as $user) : ?>
    <div>
    Name : <a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['nickname']) ?></a>
    </div>
    <div>
    Email : <?= htmlspecialchars($user['email']) ?>
    </div>
<?php endforeach ?>
</table>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a>
<a href="?page=<?= $page + 1 ?>">Next</a>
